stages:
  - update
update:
  image: node:lts
  stage: update
  only:
    - dev
  tags:
    - k8s
  before_script:
    - echo "${UPDATER_ENV}" | tr -d '\r' > ./.env
    - npm install
    - npm run lint
  script:
    - npm run update
  artifacts:
    expire_in: 1 month
    paths:
      - log.txt
